### ISSUE TITLE
Elérhetőség

### ISSUE THREAD

**Issue by Balint66** [SakiiCode/e_pluto#1]
Üdvözlet!
A másik repo-d on láttam discord szerver meghívót, ami sajnos már lejárt.
Szeretnék rólad erről a projektről személyesen, négyszemközt beszélni, ezért jó lenne, ha adnál egy elérhetőséget, ahol tudnánk beszélni.

**Comment by SakiiCode** [comment]
Ok, frissítettem a discord linket, de Sakii#4740 néven könnyebben megtalálsz

**Comment by Balint66** [comment]
Rendben, egy friend request-et küldtem is.
